version: '3.8'

services:
  gigachat-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gigachat-proxy
    ports:
      - "3001:3001"
    environment:
      - LOG_LEVEL=INFO
      - LOG_USE_COLOR=true
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s